project_id = "grwxnxuflxknflwvwnjx"

[functions.create-admin-user]
verify_jwt = true

[functions.analyze-recent-activity]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.reset-preceptor-password]
verify_jwt = true

[functions.create-student-user]
verify_jwt = true

[functions.create-coordenador-user]
verify_jwt = true

[functions.check-disciplinas-status]
verify_jwt = false

[functions.create-preceptor-user]
verify_jwt = true

[functions.update-preceptor-user]
verify_jwt = true

[functions.generate-turmas-praticas]
verify_jwt = true
